package cn.pax.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table GOODS.
 */
public class Goods {

    private Long id;
    private Integer pId;
    private Integer aId;
    private String img;
    private String category;
    private Double price = 0.0;
    private Double finalPrice = 0.0;//商品最终单价 add ljp 20151116
    private String name;
    private Integer num;
    private Boolean soldOut;
    private String barCode;
    private String pinyinCode;
    private String unit;
    private Integer state;
    private String unitName;
    private Integer goodsSettleFlag; // 1 - 打折 0- 不打折
    private Double inventory;
    private Double goodsDiscount = 1d;//商品折扣 add ljp 20151105
    private Double finalDiscount = 1d;//商品最终折扣 add ljp 20151116
    private int digitScale;
    private String specifications;//商品规格2015-09-21新增 聂久乾
    private String goodsNo;//货号 2015-09-24 新增 聂久乾
    private Long goodsId;//商品编号 2015-09-24 新增 聂久乾
    private Integer syncStatus;//商品同步至服务端状态 2-未同步，0-已同步 2015-10-26 聂久乾\

    private double memberDiscount;//会员折扣

    private double orderDiscount=1d;//整单折扣

    public double getOrderDiscount() {
        return orderDiscount;
    }

    public void setOrderDiscount(double orderDiscount) {
        this.orderDiscount = orderDiscount;
    }

    public double getMemberDiscount() {
        return memberDiscount;
    }

    public void setMemberDiscount(double memberDiscount) {
        this.memberDiscount = memberDiscount;
    }

    /**
     * 是否是赠送的
     * 0-不送，1-送
     */
    private Integer sendFlag;

    public Integer getSendFlag() {
        return sendFlag;
    }

    public void setSendFlag(Integer sendFlag) {
        this.sendFlag = sendFlag;
    }

    public Goods() {
    }

    public Goods(Long id) {
        this.id = id;
    }

    public Goods(Long id, Integer pId, Integer aId, String img, String category, Double price, String name, Integer num, Boolean soldOut, Double promoPrice, String barCode, String pinyinCode, String unit, Integer state, String unitName, Integer goodsSettleFlag, String specifications, String goodsNo, Long goodsId, Integer syncStatus) {
        this.id = id;
        this.pId = pId;
        this.aId = aId;
        this.img = img;
        this.category = category;
        this.price = price;
        this.name = name;
        this.num = num;
        this.soldOut = soldOut;
        this.barCode = barCode;
        this.pinyinCode = pinyinCode;
        this.unit = unit;
        this.state = state;
        this.unitName = unitName;
        this.goodsSettleFlag = goodsSettleFlag;
        this.specifications = specifications;
        this.goodsNo = goodsNo;
        this.goodsId = goodsId;
        this.syncStatus = syncStatus;
    }

    //新增规格
    public Goods(Long id, Long goodsId, Integer pId, Integer aId, String img, String category, Double price, String name, Integer num, Boolean soldOut, String barCode, String pinyinCode, String unit, Integer state, String unitName, Integer goodsSettleFlag, Double inventory, int digitScale, String specifications, String goodsNo, Integer syncStatus) {
        this.id = id;
        this.goodsId = goodsId;
        this.pId = pId;
        this.aId = aId;
        this.img = img;
        this.category = category;
        this.price = price;
        this.name = name;
        this.num = num;
        this.soldOut = soldOut;
        this.barCode = barCode;
        this.pinyinCode = pinyinCode;
        this.unit = unit;
        this.state = state;
        this.unitName = unitName;
        this.goodsSettleFlag = goodsSettleFlag;
        this.inventory = inventory;
        this.digitScale = digitScale;
        this.specifications = specifications;
        this.goodsNo = goodsNo;
        this.syncStatus = syncStatus;
    }

    @Override
    public String toString() {
        return "Goods{" +
                "id=" + id +
                ", pId=" + pId +
                ", aId=" + aId +
                ", img='" + img + '\'' +
                ", category='" + category + '\'' +
                ", price=" + price +
                ", name='" + name + '\'' +
                ", num=" + num +
                ", soldOut=" + soldOut +
                ", barCode='" + barCode + '\'' +
                ", pinyinCode='" + pinyinCode + '\'' +
                ", unit='" + unit + '\'' +
                ", state=" + state +
                ", unitName='" + unitName + '\'' +
                ", goodsSettleFlag=" + goodsSettleFlag +
                ", inventory=" + inventory +
                ", digitScale=" + digitScale +
                ", specifications='" + specifications + '\'' +
                ", goodsNo='" + goodsNo + '\'' +
                ", goodsId=" + goodsId +
                ", syncStatus=" + syncStatus +
                '}';
    }

    public Long getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPId() {
        return pId;
    }

    public void setPId(Integer pId) {
        this.pId = pId;
    }

    public Integer getAId() {
        return aId;
    }

    public void setAId(Integer aId) {
        this.aId = aId;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public Boolean getSoldOut() {
        return soldOut;
    }

    public void setSoldOut(Boolean soldOut) {
        this.soldOut = soldOut;
    }

    public String getBarCode() {
        return barCode;
    }

    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    public String getPinyinCode() {
        return pinyinCode;
    }

    public void setPinyinCode(String pinyinCode) {
        this.pinyinCode = pinyinCode;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public Integer getGoodsSettleFlag() {
        return goodsSettleFlag;
    }

    public void setGoodsSettleFlag(Integer goodsSettleFlag) {
        this.goodsSettleFlag = goodsSettleFlag;
    }

    public Double getInventory() {
        return inventory;
    }

    public void setInventory(Double inventory) {
        this.inventory = inventory;
    }

    public int getDigitScale() {
        return digitScale;
    }

    public void setDigitScale(int digitScale) {
        this.digitScale = digitScale;
    }

    public String getSpecifications() {
        return specifications;
    }
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    public String getGoodsNo() {
        return goodsNo;
    }

    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo;
    }

    public Integer getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(Integer syncStatus) {
        this.syncStatus = syncStatus;
    }

    public Double getGoodsDiscount() {
        return goodsDiscount;
    }

    public void setGoodsDiscount(Double goodsDiscount) {
        this.goodsDiscount = goodsDiscount;
    }

    public Double getFinalDiscount() {
        return finalDiscount;
    }

    public void setFinalDiscount(Double finalDiscount) {
        this.finalDiscount = finalDiscount;
    }

    public Double getFinalPrice() {
        return finalPrice;
    }

    public void setFinalPrice(Double finalPrice) {
        this.finalPrice = finalPrice;
    }
}
